/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import studentgroupmaker.*;

/**
 *
 * @author Tom
 */
public class StudentPickerGUI extends javax.swing.JFrame {

    int groupNumber = 1;
    ArrayList<Student> groupStudents = new ArrayList();
    boolean groupConfirm = false;

    /**
     * Creates new form StudentPickerGUI
     */
    public StudentPickerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnGroups = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstGroups = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        btnAddStudentToGroup = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstGroupStudents = new javax.swing.JList<>();
        btnClearGroups = new javax.swing.JButton();
        btnConfirmGroup = new javax.swing.JButton();
        lblGroupNumber = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        btnCreateStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSkills = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnAddSkill = new javax.swing.JButton();
        btnRemoveSkill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSkillChoice = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstStudents = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Grouper");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnGroups.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGroups.setText("Generate Groups");
        btnGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupsActionPerformed(evt);
            }
        });

        lstGroups.setModel(groupsListManager);
        jScrollPane4.setViewportView(lstGroups);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Groups");

        btnAddStudentToGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddStudentToGroup.setText("Add Selected Student");
        btnAddStudentToGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentToGroupActionPerformed(evt);
            }
        });

        lstGroupStudents.setModel(studentsListManager);
        jScrollPane5.setViewportView(lstGroupStudents);

        btnClearGroups.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClearGroups.setText("Clear Groups");
        btnClearGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearGroupsActionPerformed(evt);
            }
        });

        btnConfirmGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConfirmGroup.setText("Confirm Group");
        btnConfirmGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmGroupActionPerformed(evt);
            }
        });

        lblGroupNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGroupNumber.setText("Group Number: 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGroups)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAddStudentToGroup))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(btnClearGroups))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnConfirmGroup)
                                .addGap(27, 27, 27)
                                .addComponent(lblGroupNumber)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(btnGroups)
                            .addGap(65, 65, 65)
                            .addComponent(btnAddStudentToGroup)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnConfirmGroup)
                                .addComponent(lblGroupNumber))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClearGroups))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tbdPane.addTab("Groups", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("First Name:");

        txtFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Last Name:");

        txtLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLName.setToolTipText("");

        btnCreateStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCreateStudent.setText("Create Student");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        lstSkills.setModel(studentSkillsListManager);
        lstSkills.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstSkills);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Rolls");

        btnAddSkill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddSkill.setText("Add Rolls");
        btnAddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSkillActionPerformed(evt);
            }
        });

        btnRemoveSkill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoveSkill.setText("Remove Rolls");
        btnRemoveSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSkillActionPerformed(evt);
            }
        });

        lstSkillChoice.setModel(studentSkillChoiceListManager);
        studentSkillChoiceListManager.addElement("Team Leader");
        studentSkillChoiceListManager.addElement("Requirements");
        studentSkillChoiceListManager.addElement("UI Design");
        studentSkillChoiceListManager.addElement("System Design");
        studentSkillChoiceListManager.addElement("Development");
        studentSkillChoiceListManager.addElement("Testing");
        lstSkillChoice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstSkillChoice.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Team Leader", "Requirments", "UI Design", "System Design", "Development", "Testing" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstSkillChoice);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student's Rolls");

        lstStudents.setModel(studentsListManager);
        jScrollPane3.setViewportView(lstStudents);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Students");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLName))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRemoveSkill)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddSkill)
                                        .addGap(23, 23, 23)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnCreateStudent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAddSkill)
                        .addGap(38, 38, 38)
                        .addComponent(btnRemoveSkill))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateStudent)
                .addContainerGap(363, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbdPane.addTab("Students", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        ArrayList<String> roles = new ArrayList();
        for (int i = 0; i < studentSkillsListManager.size(); i++) {
            roles.add(studentSkillsListManager.get(i).toString());
        }
        StudentGroupMaker.createStudent(fName, lName, roles);
        studentsListManager.addElement(fName);
        txtFName.setText("");
        txtLName.setText("");
        studentSkillsListManager.clear();
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSkillActionPerformed
        if (studentSkillsListManager.getSize() <= 4) {
            int selected = lstSkillChoice.getSelectedIndex();
            if (!studentSkillsListManager.contains(studentSkillChoiceListManager.get(selected))) {
                studentSkillsListManager.addElement(studentSkillChoiceListManager.get(selected));
            } else {
                JOptionPane.showMessageDialog(null, "Student already has this skill.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Student can only have 5 skills.");
        }
    }//GEN-LAST:event_btnAddSkillActionPerformed

    private void btnRemoveSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSkillActionPerformed
        if (studentSkillsListManager.getSize() >= 1) {
            int selected = lstSkills.getSelectedIndex();
            studentSkillsListManager.remove(selected);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a skill to remove");
        }
    }//GEN-LAST:event_btnRemoveSkillActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            StudentGroupMaker.saveData();
        } catch (IOException ex) {
            Logger.getLogger(StudentPickerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupsActionPerformed
        if (groupsListManager.isEmpty()) {
            StudentGroupMaker.makeGroups();
        } else {
            JOptionPane.showMessageDialog(null, "Groups already made");

        }
    }//GEN-LAST:event_btnGroupsActionPerformed

    private void btnClearGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearGroupsActionPerformed
        StudentGroupMaker.clearGroups();
        groupsListManager.clear();
        JOptionPane.showMessageDialog(null, "Groups Cleared");
    }//GEN-LAST:event_btnClearGroupsActionPerformed

    private void btnAddStudentToGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentToGroupActionPerformed
        String student = lstGroupStudents.getSelectedValue();
        groupConfirm = false;
        groupsListManager.addElement("Group " + groupNumber + " :" + student);
        for (int i = 0; i < StudentGroupMaker.getStudentSize(); i++) {
            if (StudentGroupMaker.getStudent(i).getfName().equals(student)) {
                groupStudents.add(StudentGroupMaker.getStudent(i));
            }
        }
    }//GEN-LAST:event_btnAddStudentToGroupActionPerformed

    private void btnConfirmGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmGroupActionPerformed
        StudentGroupMaker.createGroup(groupStudents, groupNumber);
        groupNumber++;
        lblGroupNumber.setText("Group Number: " + groupNumber);
        groupConfirm = true;

    }//GEN-LAST:event_btnConfirmGroupActionPerformed

    public static DefaultListModel studentsListManager = new DefaultListModel();
    public static DefaultListModel groupsListManager = new DefaultListModel();
    DefaultListModel studentSkillsListManager = new DefaultListModel();
    DefaultListModel studentSkillChoiceListManager = new DefaultListModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSkill;
    private javax.swing.JButton btnAddStudentToGroup;
    private javax.swing.JButton btnClearGroups;
    private javax.swing.JButton btnConfirmGroup;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnGroups;
    private javax.swing.JButton btnRemoveSkill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGroupNumber;
    private javax.swing.JList<String> lstGroupStudents;
    private javax.swing.JList<String> lstGroups;
    private javax.swing.JList<String> lstSkillChoice;
    private javax.swing.JList<String> lstSkills;
    private javax.swing.JList<String> lstStudents;
    private javax.swing.JTabbedPane tbdPane;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    // End of variables declaration//GEN-END:variables
}
